apiVersion: v1
kind: Service
metadata:
  name: inventory-ms
spec:
  selector:
    app: inventory-ms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082   # This must be between 30000–32767
  type: NodePort
