apiVersion: v1
kind: Service
metadata:
  name: order-ms
spec:
  selector:
    app: order-ms
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081   # This must be between 30000–32767
  type: NodePort
