apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-ms
  template:
    metadata:
      labels:
        app: product-ms
    spec:
      containers:
        - name: product-ms
          image: product-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
