apiVersion: v1
kind: Service
metadata:
  name: product-ms
spec:
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080   # This must be between 30000–32767
  type: NodePort
